#!/bin/bash

#
# gen_descriptions dir_with_useful.txt_files dir_with_.exe_files output_file
#
# example: 
# ./gen_descriptions /data/Malware/Locky_1_and_2 /data/Malware/Locky-Cam SamplesDescriptions.txt
#

if [ $# -ne 3 ]
  then
    echo "Invalid number of parameters."
    exit 1
fi

USEFULS_DIR=$1
EXE_DIR=$2
OUTFILE=$3

USEFULS=$(cat $(find $USEFULS_DIR -name "*useful.txt"))
MD5SUMS=$(md5sum $(find $EXE_DIR -name "*.exe"))
ENTRYFUNCS=$(echo "$USEFULS" | grep DLL | awk -F ', ' '{print $3}' | tr -s '\n' '\n' | uniq) 

while read func; do 
    echo -e "\n\nEntryFunction: $func" >> $OUTFILE 
    HASHES=$(echo "$USEFULS" | grep $func | awk -F ', ' '{if(length($1)==32) {print $1}}')
    while read hash; do
        echo "Current hash: $hash"
        FILEPATH=$(echo "$MD5SUMS" | grep $hash | awk -F '  ' '{print $2}')
        FILENAME=$(basename $FILEPATH) 
        echo "$hash $FILENAME" >> $OUTFILE  
    done <<< "$HASHES"
done <<< "$ENTRYFUNCS"

